name: Keep Render API Endpoint Awake

on:
  schedule:
    - cron: '*/14 * * * *' # Every 14 minutes
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: API Web Service
        run: |
          echo "Pinging Render at $(date -u)..."
          curl -s -w " %{http_code}" https://products-management-portal-backend.onrender.com/ || echo "Ping failed"